// <auto-generated />
using System;
using CalisanSistemi.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalisanSistemi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalisanSistemi.Model.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("CalisanSistemi.Model.Departman", b =>
                {
                    b.Property<int>("DepartmanNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmanNo"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CalisanSayisi")
                        .HasColumnType("int");

                    b.Property<string>("DepartmanAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmanNo");

                    b.ToTable("Departmans");
                });

            modelBuilder.Entity("CalisanSistemi.Model.Gorev", b =>
                {
                    b.Property<int>("GorevId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GorevId"));

                    b.Property<int>("GorevTipId")
                        .HasColumnType("int");

                    b.Property<int>("PersonelNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SonTarih")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TamamlandiMi")
                        .HasColumnType("bit");

                    b.HasKey("GorevId");

                    b.HasIndex("GorevTipId");

                    b.HasIndex("PersonelNo");

                    b.ToTable("Gorevs");
                });

            modelBuilder.Entity("CalisanSistemi.Model.GorevTipi", b =>
                {
                    b.Property<int>("GorevTipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GorevTipId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("GorevTipId");

                    b.ToTable("GorevTipis");
                });

            modelBuilder.Entity("CalisanSistemi.Model.Personel", b =>
                {
                    b.Property<int>("PersonelNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelNo"));

                    b.Property<int>("DepartmanNo")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Maas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Meslek")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PersonelAdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yas")
                        .HasColumnType("int");

                    b.HasKey("PersonelNo");

                    b.HasIndex("DepartmanNo");

                    b.ToTable("Personels");
                });

            modelBuilder.Entity("CalisanSistemi.Model.Gorev", b =>
                {
                    b.HasOne("CalisanSistemi.Model.GorevTipi", "GorevTipi")
                        .WithMany()
                        .HasForeignKey("GorevTipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalisanSistemi.Model.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GorevTipi");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("CalisanSistemi.Model.Personel", b =>
                {
                    b.HasOne("CalisanSistemi.Model.Departman", "Departman")
                        .WithMany()
                        .HasForeignKey("DepartmanNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departman");
                });
#pragma warning restore 612, 618
        }
    }
}
